source 'https://github.com/CocoaPods/Specs.git'
# source 'http://gitlab.ivedeng.com/veui/vdpod.git'
platform :ios, '10.0'

use_frameworks!

target 'VEUI_Example' do
  pod 'VEUI', :path => '../VEUI.podspec'
  pod 'FDFullscreenPopGesture', '1.1'
  pod 'SDWebImage'
  
  target 'VEUI_Tests' do
    inherit! :search_paths
    pod 'FBSnapshotTestCase'
  end
end

post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'
       end
    end
  end
end
